DROP TABLE shelter IF EXISTS;
DROP TABLE dog IF EXISTS;

CREATE TABLE dog (
id bigint generated by default as identity, 
age integer, 
available varchar(255), 
breed varchar(255), 
colour varchar(255), 
name varchar(255), 
shelter_id bigint, 
primary key (id)
);

create table shelter (
id bigint generated by default as identity, 
address_line varchar(255), 
name varchar(255), 
postcode varchar(255), 
primary key (id)
);

alter table dog 
add constraint FK2uaq25owutkvgghtrt2b88dg4 
foreign key (shelter_id) references shelter on delete cascade;